-- Conductix 2.0 - esquema reproducible para Supabase
create extension if not exists pgcrypto;
create or replace function public.conductix_touch_server_updated_at() returns trigger language plpgsql security invoker set search_path=public as $$ begin new.server_updated_at=now(); return new; end; $$;

create table if not exists public.conductix_institutions (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), name text not null, notes text not null default '', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_ensembles (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), institution_id uuid not null, name text not null, type_label text not null default '', academic_mode_enabled boolean not null default false, active boolean not null default true, foreign key(user_id,institution_id) references public.conductix_institutions(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_categories (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), ensemble_id uuid not null, name text not null, display_order integer not null default 0, active boolean not null default true, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_academic_levels (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), institution_id uuid, ensemble_id uuid, name text not null, display_order integer not null default 0, active boolean not null default true, check(num_nonnulls(institution_id,ensemble_id)=1), foreign key(user_id,institution_id) references public.conductix_institutions(user_id,id) on delete cascade, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_members (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), ensemble_id uuid not null, category_id uuid, level_id uuid, first_name text not null, last_name text not null default '', phone text not null default '', email text not null default '', birth_date date, join_date date, leave_date date, general_notes text not null default '', medical_info text not null default '', active boolean not null default true, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, foreign key(user_id,category_id) references public.conductix_categories(user_id,id) on delete restrict, foreign key(user_id,level_id) references public.conductix_academic_levels(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_member_contacts (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), member_id uuid not null, contact_type text not null default '', name text not null default '', relationship text not null default '', display_order integer not null default 0, email text not null default '', phone text not null default '', guardian_name text not null default '', guardian_phone text not null default '', emergency_contact text not null default '', medical_note text not null default '', foreign key(user_id,member_id) references public.conductix_members(user_id,id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_member_notes (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), member_id uuid not null, note_date date, note text not null default '', title text not null default '', body text not null default '', foreign key(user_id,member_id) references public.conductix_members(user_id,id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_events (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), ensemble_id uuid, event_date date not null, start_time time, title text not null, event_type text not null default '', location text not null default '', notes text not null default '', foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_attendance_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), ensemble_id uuid not null, session_date date not null, session_type text not null default 'regular', linked_event_id uuid, notes text not null default '', foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, foreign key(user_id,linked_event_id) references public.conductix_events(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_attendance_records (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), session_id uuid not null, member_id uuid not null, present boolean not null default false, late boolean not null default false, notes text not null default '', foreign key(user_id,session_id) references public.conductix_attendance_sessions(user_id,id) on delete cascade, foreign key(user_id,member_id) references public.conductix_members(user_id,id) on delete cascade, unique(user_id,session_id,member_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_repertoire_items (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), ensemble_id uuid, title text not null, composer text not null default '', arranger text not null default '', piece_type text not null default '', status text not null default '', notes text not null default '', active boolean not null default true, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_repertoire_ensembles (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), repertoire_item_id uuid not null, ensemble_id uuid not null, foreign key(user_id,repertoire_item_id) references public.conductix_repertoire_items(user_id,id) on delete cascade, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, unique(user_id,repertoire_item_id,ensemble_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_planned_concerts (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), ensemble_id uuid, title text not null, concert_date date not null, start_time time, location text not null default '', notes text not null default '', weekly_schedule jsonb not null default '{}'::jsonb, regular_weekdays text not null default '', regular_start_time time, regular_end_time time, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_concert_ensembles (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), concert_id uuid not null, ensemble_id uuid not null, display_order integer not null default 0, foreign key(user_id,concert_id) references public.conductix_planned_concerts(user_id,id) on delete cascade, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, unique(user_id,concert_id,ensemble_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_extra_rehearsals (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), concert_id uuid not null, ensemble_id uuid, rehearsal_date date not null, start_time time, end_time time, duration_minutes integer not null default 60 check(duration_minutes>0), notes text not null default '', foreign key(user_id,concert_id) references public.conductix_planned_concerts(user_id,id) on delete cascade, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_planning_blocks (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), concert_id uuid, ensemble_id uuid, block_date date not null, block_type text not null, block_scope text not null default 'ensemble', notes text not null default '', foreign key(user_id,concert_id) references public.conductix_planned_concerts(user_id,id) on delete cascade, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_concert_programs (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), concert_id uuid not null, title text not null default '', subtitle text not null default '', notes text not null default '', foreign key(user_id,concert_id) references public.conductix_planned_concerts(user_id,id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_concert_program_items (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), program_id uuid not null, repertoire_item_id uuid, item_type text not null default 'repertoire', title text not null default '', composer text not null default '', arranger text not null default '', subtitle text not null default '', ensemble_label text not null default '', notes text not null default '', external_title text not null default '', external_composer text not null default '', external_arranger text not null default '', external_piece_type text not null default '', external_status text not null default '', display_order integer not null default 0, foreign key(user_id,program_id) references public.conductix_concert_programs(user_id,id) on delete cascade, foreign key(user_id,repertoire_item_id) references public.conductix_repertoire_items(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_concert_program_item_ensembles (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), program_item_id uuid not null, ensemble_id uuid not null, foreign key(user_id,program_item_id) references public.conductix_concert_program_items(user_id,id) on delete cascade, foreign key(user_id,ensemble_id) references public.conductix_ensembles(user_id,id) on delete cascade, unique(user_id,program_item_id,ensemble_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

create table if not exists public.conductix_concert_program_soloists (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid(), program_item_id uuid not null, member_id uuid, guest_name text not null default '', soloist_name text not null default '', role text not null default '', display_order integer not null default 0, check(member_id is not null or length(trim(guest_name))>0 or length(trim(soloist_name))>0), foreign key(user_id,program_item_id) references public.conductix_concert_program_items(user_id,id) on delete cascade, foreign key(user_id,member_id) references public.conductix_members(user_id,id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), client_updated_at timestamptz not null default now(), server_updated_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id,id));

do $$ declare t text; begin foreach t in array array['conductix_institutions','conductix_ensembles','conductix_categories','conductix_academic_levels','conductix_members','conductix_member_contacts','conductix_member_notes','conductix_events','conductix_attendance_sessions','conductix_attendance_records','conductix_repertoire_items','conductix_repertoire_ensembles','conductix_planned_concerts','conductix_concert_ensembles','conductix_extra_rehearsals','conductix_planning_blocks','conductix_concert_programs','conductix_concert_program_items','conductix_concert_program_item_ensembles','conductix_concert_program_soloists'] loop execute format('drop trigger if exists conductix_touch_server_updated_at on public.%I',t); execute format('create trigger conductix_touch_server_updated_at before update on public.%I for each row execute function public.conductix_touch_server_updated_at()',t); execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists conductix_owner_all on public.%I',t); execute format('create policy conductix_owner_all on public.%I for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id)',t); execute format('revoke all on public.%I from anon',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end $$;
