const enc=new TextEncoder();
function crc32(bytes){let c=~0;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xEDB88320:0);}return(~c)>>>0;}
function u16(n){return[n&255,(n>>>8)&255]}
function u32(n){return[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function zip(files){let parts=[],central=[],off=0;for(const[name,text]of Object.entries(files)){const n=enc.encode(name),d=enc.encode(text),crc=crc32(d);const h=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(d.length),...u32(d.length),...u16(n.length),...u16(0),...n]);parts.push(h,d);const ch=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(d.length),...u32(d.length),...u16(n.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(off),...n]);central.push(ch);off+=h.length+d.length;}const csize=central.reduce((n,x)=>n+x.length,0),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(central.length),...u16(central.length),...u32(csize),...u32(off),...u16(0)]);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const stamp=()=>new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date());
function paragraph(text,bold=false,size=null){return `<w:p><w:r><w:rPr>${bold?'<w:b/>':''}${size?`<w:sz w:val="${size}"/>`:''}</w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p>`;}
function cell(text,bold=false,size=20){return `<w:tc><w:p><w:r><w:rPr>${bold?'<w:b/>':''}<w:sz w:val="${size}"/></w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p></w:tc>`;}
function row(values,header=false,size=20){return `<w:tr>${values.map(v=>cell(v,header,size)).join('')}</w:tr>`;}
function table(headers,rows,size=20){return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="single" w:sz="4"/><w:left w:val="single" w:sz="4"/><w:bottom w:val="single" w:sz="4"/><w:right w:val="single" w:sz="4"/><w:insideH w:val="single" w:sz="4"/><w:insideV w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>${row(headers,true,size)}${rows.map(r=>row(r,false,size)).join('')}</w:tbl>`;}
function sect(landscape=false){return landscape?'<w:sectPr><w:pgSz w:w="16838" w:h="11906" w:orient="landscape"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr>':'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr>';}
function packageDoc(body,landscape=false){return zip({'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/document.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}${sect(landscape)}</w:body></w:document>`});}
export function makeDocx(title,lines){const body=[paragraph(title,true,32),...lines.map(x=>paragraph(x))].join('');return packageDoc(body,false);}
export function makeTableDocx(title,rows,{landscape=false,fontSizeHalfPoints=20}={}){if(!rows?.length)return null;const headers=Object.keys(rows[0]);const matrix=rows.map(r=>headers.map(h=>String(r[h]??'')));const body=paragraph(`Conductix - ${title}`,true,32)+paragraph(`Exportado el ${stamp()}`)+table(headers,matrix,fontSizeHalfPoints);return packageDoc(body,landscape);}
export function makeAttendanceDocx(title,monthSections){let body=paragraph(`Conductix - ${title}`,true,32)+paragraph(`Exportado el ${stamp()}`);for(const section of monthSections){body+=paragraph(section.title,true,26)+table(section.headers,section.rows,24)+paragraph('Leyenda: A = asistió | X = falta | R = retardo');}return packageDoc(body,true);}
export function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
