package com.conductix.app;

import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.view.View;import android.webkit.WebResourceRequest;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;import androidx.core.graphics.Insets;import androidx.core.view.ViewCompat;import androidx.core.view.WindowCompat;import androidx.core.view.WindowInsetsCompat;import android.widget.FrameLayout;

public class MainActivity extends Activity {
    private static final String APP_URL="https://yoandarz.github.io/conductix/"; private static final String HOST="yoandarz.github.io"; private WebView webView;
    @Override public void onCreate(Bundle state){super.onCreate(state);WindowCompat.setDecorFitsSystemWindows(getWindow(),false);FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(36,20,61));webView=new WebView(this);root.addView(webView,new FrameLayout.LayoutParams(-1,-1));setContentView(root);ViewCompat.setOnApplyWindowInsetsListener(root,(v,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.displayCutout());FrameLayout.LayoutParams lp=(FrameLayout.LayoutParams)webView.getLayoutParams();lp.topMargin=bars.top;lp.bottomMargin=bars.bottom;lp.leftMargin=bars.left;lp.rightMargin=bars.right;webView.setLayoutParams(lp);return insets;});ViewCompat.requestApplyInsets(root);configure();webView.loadUrl(APP_URL);}
    private void configure(){WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);webView.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return route(r.getUrl());}@Override public boolean shouldOverrideUrlLoading(WebView v,String url){return route(Uri.parse(url));}private boolean route(Uri u){if("https".equalsIgnoreCase(u.getScheme())&&HOST.equalsIgnoreCase(u.getHost()))return false;startActivity(new Intent(Intent.ACTION_VIEW,u));return true;}});}
    @Override public void onBackPressed(){if(webView.canGoBack())webView.goBack();else super.onBackPressed();}
}
